User_message_blueprint/project/messages/models.py
from project import db

class Message(db.Model):
    __tablename__ = 'message'

    id = db.Column(db.Integer, primary_key=True)
    message = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, message, user_id):
    	self.message = message
    	self.user_id = user_id

User_message_blueprint/project/users/models.py
from project import db, bcrypt
from project.messages.models import Message
from flask_login import UserMixin


class User(db.Model,UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.Text, unique=True)
    password = db.Column(db.Text)
    email = db.Column(db.Text)
    first_name = db.Column(db.Text)
    last_name = db.Column(db.Text)
    messages = db.relationship('Message', backref='user',lazy='dynamic')

    def __init__(self,username, password, email, first_name, last_name):
        self.username = username
        self.password = bcrypt.generate_password_hash(password).decode('UTF-8')
        self.email = email
        self.first_name = first_name
        self.last_name = last_name

User_message_blueprint/project/messages/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class MessageForm(FlaskForm):
    message = StringField('message', validators=[DataRequired()])

User_message_blueprint/project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class UserForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = StringField('password', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired()])
    first_name = StringField('first_name', validators=[DataRequired()])
    last_name = StringField('last_name', validators=[DataRequired()])

class LoginForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = StringField('password', validators=[DataRequired()])


class EditForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired()])
    first_name = StringField('first_name', validators=[DataRequired()])
    last_name = StringField('last_name', validators=[DataRequired()])

User_message_blueprint/app.py
from project import app

if __name__ == '__main__':
    app.run(debug=True, port=3000)

User_message_blueprint/project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_modus import Modus
from flask_bcrypt import Bcrypt
import os
from flask_login import LoginManager

app = Flask(__name__)
login_manager = LoginManager()
modus = Modus(app)
bcrypt = Bcrypt(app)
login_manager.init_app(app)
login_manager.login_view = "users.login"

app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY') or 'Implement me later please'
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres://localhost/users-blueprints'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

# import a blueprint that we will create
from project.users.views import users_blueprint
from project.messages.views import messages_blueprint
from project.users.models import User
# register our blueprints with the application
app.register_blueprint(users_blueprint, url_prefix='/users')
app.register_blueprint(messages_blueprint, url_prefix='/users/<int:id>/messages')

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@app.route('/')
def root():
    return "HELLO BLUEPRINTS!"

User_message_blueprint/project/messages/views.py
from flask import redirect, render_template, request, url_for, Blueprint
from project.messages.models import Message
from project.users.models import User
from project.messages.forms import MessageForm
from project import db

messages_blueprint = Blueprint(
    'messages',
    __name__,
    template_folder='templates'
)

@messages_blueprint.route('/', methods =["GET", "POST"])
def index(id):
	if request.method == "POST":
		form = MessageForm()
		if form.validate():
			new_message = Message(request.form['message'], id)
			db.session.add(new_message)
			db.session.commit()
			return redirect(url_for('messages.index',id=id))
		return render_template('messages/new.html', form=form)
	return render_template('messages/index.html', user=User.query.get(id), messages=User.query.get(id).messages)

@messages_blueprint.route('/new')
def new(id):
	user = User.query.get(id)
	form = MessageForm()
	return render_template('messages/new.html', form=form, user=user)

@messages_blueprint.route('/<int:mid>/edit')
def edit(id,mid):
	user = User.query.get(id)
	message=Message.query.get(mid)
	form = MessageForm(obj=message)
	return render_template('messages/edit.html', form=form, message=message, user=user)

@messages_blueprint.route('/<int:mid>', methods =["GET", "PATCH", "DELETE"])
def show(id,mid):
	user = User.query.get(id)
	found_message = Message.query.get(mid)
	if request.method == b"PATCH":
		form = MessageForm(request.form)
		if form.validate():
			found_message.message = request.form['message']
			db.session.add(found_message)
			db.session.commit()
			return redirect(url_for('messages.index', id=id))
		return render_template('messages/edit.html', form=form, message=found_message)
	if request.method == b"DELETE":
		db.session.delete(found_message)
		db.session.commit()
		return redirect(url_for('messages.index', id=id))
	return render_template('messages/show.html', message=found_message, user=user)

User_message_blueprint/project/users/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash
from project.users.models import User
from project.users.forms import UserForm, LoginForm, EditForm
from project import db, bcrypt
from flask_login import login_user, logout_user, current_user, login_required

users_blueprint = Blueprint(
    'users',
    __name__,
    template_folder='templates'
)


@users_blueprint.route('/', methods =["GET", "POST"])
def index():
	if request.method == "POST":
		form = UserForm(request.form)
		if form.validate():
			new_user = User(request.form['username'],request.form['password'], request.form['email'], request.form['first_name'], request.form['last_name'])
			db.session.add(new_user)
			db.session.commit()
			return redirect(url_for('users.index'))
		return render_template('users/new.html', form=form)
	return render_template('users/index.html', users=User.query.all())

@users_blueprint.route('/login', methods=['GET','POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.data['username']).first()
        if user and bcrypt.check_password_hash(user.password, form.data['password']):
            login_user(user)
            flash("You have successfully logged in as {}".format(user.username))
            return redirect(url_for('messages.index', id=user.id))
        flash("Invalid credentials.")
    return render_template('users/login.html', form=form)

@users_blueprint.route('/logout')
def logout():
    logout_user()
    flash('Sucessfully logged out!')
    return redirect(url_for('users.login'))


@users_blueprint.route('/new')
def new():
    form = UserForm()
    return render_template('users/new.html', form=form)

@users_blueprint.route('/<int:id>/edit')
@login_required
def edit(id):
	users=User.query.get(id)
	form = EditForm(obj=users)
	return render_template('users/edit.html', form=form, user=users)

@users_blueprint.route('/<int:id>', methods =["GET", "PATCH", "DELETE"])
@login_required
def show(id):
    found_user = User.query.get(id)
    if request.method == b"PATCH":
        form = EditForm(request.form)
        if form.validate():
            found_user.first_name = request.form['first_name']
            found_user.last_name = request.form['last_name']
            found_user.email = request.form['email']
            found_user.username = request.form['username']
            db.session.add(found_user)
            db.session.commit()
            return redirect(url_for('users.show', id=found_user.id))
        return render_template('users/edit.html', form=form, user=found_user)
    if request.method == b"DELETE":
        db.session.delete(found_user)
        db.session.commit()
        return redirect(url_for('users.index'))
    return render_template('users/show.html', user=found_user)

User_message_blueprint/project/messages/templates/messages/edit.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{url_for('messages.show', id=user.id, mid=message.id)}}?_method=PATCH">
  {{ form.csrf_token }}
  <p>
    {{ form.message(placeholder="Message") }}
    <span>
      {% if form.message.errors %}
        {% for error in form.message.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button type="submit">Edit message</button>
</form>
<form method="POST" action="{{url_for('messages.show', id=user.id, mid=message.id)}}?_method=DELETE">
  {{ form.csrf_token }}
  <input type="submit" value="Delete">
</form>

{% endblock %}

User_message_blueprint/project/messages/templates/messages/index.html
{% extends 'base.html' %}

{% block content %}
<h2>{{user.username}}'s messages</h2>
{% for message in messages %}
    
    <p>
        {{message.message}} says {{message.user.first_name}} <a href="{{url_for('messages.edit', id=message.user.id, mid=message.id)}}">edit</a>
        <br>
    </p>
    
{% endfor %}
    <form action="{{url_for('messages.new', id=user.id)}}">
      <input type="submit" value="Add new message">
    </form>
{% endblock %}

User_message_blueprint/project/messages/templates/messages/new.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('messages.index', id=user.id) }}">
    {{ form.csrf_token }}
  <p>
    {{ form.message(placeholder="messages") }}
    <span>
      {% if form.message.errors %}
        {% for error in form.message.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button type="submit">Add message!</button>
</form>

{% endblock %}

User_message_blueprint/project/messages/templates/messages/show.html
{% extends 'base.html' %}
{% block content %}
    <h1>Welcome to the show page!</h1>
    <p>Message:</p>
    <p>{{message.message}}</p>
    <p>Delete me?</p>

    <form method="POST" action="{{url_for('messages.show', id=user.id, mid=message.id)}}?_method=DELETE">
        <input type="submit" value="X">
    </form>

{% endblock %}

User_message_blueprint/project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blueprints App</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <style>
      .container{
        margin-top: 10%;
      }
    </style>
</head>
<body>
    {% with messages = get_flashed_messages() %} 
      {% if messages %} 
        {% for message in messages %}
          <p>{{ message }}</p>
        {% endfor %} 
      {% endif %} 
    {% endwith %}
    <div class="container text-center">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

User_message_blueprint/project/users/templates/users/edit.html
{% extends 'base.html' %}

{% block content %}
<h2>Edit {{user.username}}</h2>

<form method="POST" action="{{url_for('users.show', id=user.id)}}?_method=PATCH">
  {{ form.csrf_token }}
    <p>
    Username: {{ form.username(placeholder="Username") }}
    <span>
      {% if form.username.errors %}
        {% for error in form.username.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    Email: {{ form.email(placeholder="E-mail") }}
    <span>
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    First name: {{ form.first_name(placeholder="First Name") }}
    <span>
      {% if form.first_name.errors %}
        {% for error in form.first_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    Last name: {{ form.last_name(placeholder="Last Name") }}
    <span>
      {% if form.last_name.errors %}
        {% for error in form.last_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button type="submit">Edit User!</button>
</form>

{% endblock %}

User_message_blueprint/project/users/templates/users/index.html
{% extends 'base.html' %}

{% block content %}

{% for user in users %}
  <p>{{user.first_name}} {{user.last_name}}</p>
  <form action="{{ url_for('users.show', id=user.id) }}?_method=DELETE" method="POST">
    <button type="submit">Delete this user!</button>
  </form>
{% endfor %}

{% endblock %}

User_message_blueprint/project/users/templates/users/login.html
{% extends "base.html" %} 
{% block content %}
<h2>Log in to messenger app</h2>
<form action="{{url_for('users.login')}}" method="POST">
      {{ form.csrf_token }}
  <p>
    Username: {{ form.username(placeholder="Username") }}
    <span>
      {% if form.username.errors %}
        {% for error in form.username.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
    <p>
    Password: {{ form.password(placeholder="Password") }}
    <span>
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <input type="submit" value="Log in!">
</form>
{% endblock %}

User_message_blueprint/project/users/templates/users/new.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{url_for('users.index')}}">
    {{ form.csrf_token }}
  <p>
    {{ form.username(placeholder="Username") }}
    <span>
      {% if form.username.errors %}
        {% for error in form.username.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
    <p>
    {{ form.password(placeholder="Password") }}
    <span>
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  <p>
    {{ form.email(placeholder="E-mail") }}
    <span>
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    {{ form.first_name(placeholder="First Name") }}
    <span>
      {% if form.first_name.errors %}
        {% for error in form.first_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  <p>
    {{ form.last_name(placeholder="Last Name") }}
    <span>
      {% if form.last_name.errors %}
        {% for error in form.last_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button type="submit">Add User!</button>
</form>

{% endblock %}

User_message_blueprint/project/users/templates/users/show.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{user.username}}'s details:</h1>
    <li>First name: {{user.first_name}}</li>
    <li>Last name: {{user.last_name}}</li>
    <li>E-mail: {{user.email}}</li>


    <form action="{{url_for('users.edit', id=user.id)}}">
        <input type="submit" value="Edit user">
    </form>
    <form method="POST" action="{{url_for('users.show', id=user.id)}}?_method=DELETE">
        <input type="submit" value="Delete user">
    </form>
{% endblock %}